### ISSUE TITLE
 Invite to add your model to braindecode 

### ISSUE THREAD

**Issue by bruAristimunha** [snailpt/CTNet#1]
Hi @snailpt!

I read your paper last week, and it was very nice! I look forward to exploring the model and your advances with EEGConformer.

As I noticed in the readme, you are an open-source enthusiast, and because of that, I would like to invite you to integrate the model into braindecode. @eeyhsong made this with EEG-Conformer. https://github.com/eeyhsong/EEG-Conformer/issues/21

In my experience, having your model exposed in different places brings a lot of citations, as people tend to use it more. This increases your paper engagement and helps with the open-source community. I really believe that as an open-source community, we should spend our time building something together. We can see this on GitHub for instance, https://github.com/search?q=EEGConformer+braindecode&type=code

Braindecode is a Pytorch open-source library focused on EEG Decoding. We have a zoo of [models](https://braindecode.org/dev/api.html#models) to try to help both researchers in deep learning applying to EEG problems, as well as deep learning applying to EEG Decoding problems. More details here: https://braindecode.org/dev/index.html

I have already started the integration of the model in this PR https://github.com/braindecode/braindecode/pull/666, and your role would be to review the implementation to see if it matches your design.

I really appreciate your attention, and if you need any support in this process, I am more than available to talk and discuss any details (e-mail to contact, b.aristimunha@gmail.com)

Please let me know if this fits with your goals.

**Comment by snailpt** [comment]
Thank you very much for your request and the opportunity! I am honored that my model is being integrated into the Braindecode library. I have reviewed the implementation, and everything looks good—there are no issues from my side.

I truly appreciate your efforts in this integration, and I look forward to seeing how it contributes to the community.
